<?php
include("config.inc.php");
include("inc/iMysql_Connect.class.php");
include("inc/Mysql_Connect.class.php");
include("inc/Mysql_users.class.php");
include("inc/Mysql_art.class.php");
include("inc/Mysql_category.class.php");
include("inc/Mysql_message.class.php");
include("inc/Mysql_inc.class.php");
include("inc/function.inc.php");